### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS SHOW
GET http://localhost:3000/products/2.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Cat Backpack",
  "price": "42",
  "supplier_id": 2,
  "description": "test test test"
}

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/3.json
Content-Type: application/json

{
  "image_url": "https://assets-prd.ignimgs.com/2022/09/07/airpods-pro-1662573080387.png",
  "price": 200
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/21.json

